Todo/Todo/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^todolists/',include('mytodo.urls',namespace='todo')),
]

Todo/mytodo/urls.py
from django.conf.urls import include, url
import views as todo_views
urlpatterns = [
    url(r'^$',todo_views.todolists),
    url(r'^newfinishedtodo/(?P<id>\d+)/$',todo_views.newfinishedtodo,name='finished'),
    url(r'^rebacktodo/(?P<id>\d+)/$',todo_views.rebacktodo,name='reback'),
    url(r'^addtodo/$',todo_views.addtodo,name='add'),
    url(r'^deltodo/(?P<id>\d+)/$',todo_views.deltodo,name='del'),
    url(r'^update/(?P<id>\d+)/$',todo_views.updatetodo,name='update'),

]

Todo/mytodo/models.py
from __future__ import unicode_literals
from django.db import models

# Create your models here.

from django.contrib.auth.models import User


class Todo(models.Model):
    user = models.ForeignKey(User)
    todo = models.CharField(max_length=50)
    flag = models.CharField(max_length=2)
    priority = models.CharField(max_length=2)
    pubtime = models.DateTimeField(auto_now_add=True)

    def __unicode__(self):
        return u'%d %s %s' % (self.id, self.todo, self.flag)

    class Meta:
        ordering = ['priority', 'pubtime']

Todo/mytodo/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from models import Todo
from django.contrib.auth.models import User

# Create your views here.


def todolists(request):
	waitingtodos = Todo.objects.filter(flag=1)
	finishedtodos = Todo.objects.filter(flag=0)
	return render(request,"mytodo/todolist.html",{"waitingtodos":waitingtodos,"finishedtodos":finishedtodos})

def newfinishedtodo(request,id):
	newfinishedtodo = Todo.objects.get(id=id)
	if newfinishedtodo.flag=='1':
		newfinishedtodo.flag='0'
		newfinishedtodo.save()
	return HttpResponseRedirect("/todolists/")

def rebacktodo(request,id):
	rebacktodo = Todo.objects.get(id=id)
	if rebacktodo.flag=='0':
		rebacktodo.flag='1'
		rebacktodo.save()
	return HttpResponseRedirect("/todolists/")

def addtodo(request):
	if request.method == 'POST':
		todo = request.POST['todo']
		priority = request.POST['priority']
		user = User.objects.get(id=1)
		addtodo = Todo(user=user, todo=todo, priority=priority, flag='1')
		addtodo.save()
		todolist = Todo.objects.filter(flag=1)
		finishtodos = Todo.objects.filter(flag=0)
		return HttpResponseRedirect("/todolists/")

		
def deltodo(request,id):
	deltodo = Todo.objects.get(id=id)
	deltodo.delete()
	return HttpResponseRedirect("/todolists/")


def updatetodo(request,id):
	oldtodo = Todo.objects.get(id=id)
	if request.method == 'POST':
		oldtodo.todo = request.POST['todo']
        oldtodo.priority = request.POST['priority']
        oldtodo.save()
        return HttpResponseRedirect("/todolists/")









	

Todo/mytodo/templates/mytodo/todolist.html
<h1>待完成事务:</h1>
<style type="text/css">
	.inline-ele {
		display: inline-block;
	}
	#qwe {
		color: blue;
	}
	input {
		color: red;
	}
</style>
{% for waitingtodo in waitingtodos %}
	用户：{{waitingtodo.user}}; 事务内容：{{waitingtodo.todo}}; 紧急等级：{{waitingtodo.priority}}; 发布时间：{{waitingtodo.pubtime}}
	<form action="{% url 'todo:finished' waitingtodo.id %}" method="post" style="display:inline-block;" >
		{% csrf_token %}
		<input type="submit" value="已完成" />
	</form>
	<form action="{% url 'todo:del' waitingtodo.id %}" method="post" style="display:inline-block;">
		{% csrf_token %}
		<input type="submit" value="删除" />
	</form>
	<form action="{% url 'todo:update' waitingtodo.id %}" method="post">
		{% csrf_token %}
		<p class="inline-ele">事务内容:<input type="text" name="todo"></p>
		<p class="inline-ele">紧急等级:<input type="text" name="priority"></p>
		<input class="inline-ele" id="qwe" type="submit" value="更新" />
	</form>
{% endfor %}


<h1>已完成事务:</h1>
{% for finishedtodo in finishedtodos %}
	用户：{{finishedtodo.user}}; 事务内容：{{finishedtodo.todo}}; 紧急等级：{{finishedtodo.priority}}; 发布时间{{finishedtodo.pubtime}}
	<form action="{% url 'todo:reback' finishedtodo.id %}" method="post" style="display:inline-block;">
		{% csrf_token %}
		<input type="submit" value="重做" />
	</form>
	<form action="{% url 'todo:del' finishedtodo.id %}" method="post" style="display:inline-block;">
		{% csrf_token %}
		<input type="submit" value="删除" />
	</form>
	<form action="{% url 'todo:update' finishedtodo.id %}" method="post">
		{% csrf_token %}
		<p style="display:inline-block;">事务内容:<input type="text" name="todo"></p>
		<p style="display:inline-block;">紧急等级:<input type="text" name="priority"></p>
		<input type="submit" value="更新" style="display:inline-block;" id="qwe"/>
	</form>

{% endfor %}


<h1>添加事务:</h1>
<form action="{% url 'todo:add' %}" method="post">
	{% csrf_token %}
	<p class="inline-ele">事务内容:<input type="text" name="todo"></p>
	<p class="inline-ele">紧急等级:<input type="text" name="priority"></p>
	<input type="submit" value="添加" id="qwe" />
</form>